json_duplicate_or_invalid_format:
  code: 1000
  localization:
    en: "Json field duplicate or invalid format. Please try again"
    th: "Json มีคีย์ซ้ำกันหรือรูปแบบฟอร์เมตผิด กรุณาลองใหม่อีกครั้ง"

invalid_username:
  code: 1001
  localization:
    en: "Sorry, your username is incorrect. Please try again"
    th: "ขออภัย รหัสผู้ใช้งานของคุณไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

invalid_password:
  code: 1002
  localization:
    en: "Sorry, your password is incorrect. Please try again"
    th: "ขออภัย รหัสผ่านของคุณไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

invalid_current_password:
  code: 1003
  localization:
    en: "Sorry, your current password is incorrect. Please try again"
    th: "ขออภัย รหัสผ่านปัจจุบันของคุณไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

invalid_permission_role:
  code: 1004
  localization:
    en: "Sorry,Your permission cannot do the transaction. Please try again"
    th: "ขออภัย สิทธิ์ของคุณไม่สามารถทำรายการดังกล่าวได้ กรุณาลองใหม่อีกครั้ง"

user_not_found:
  code: 1005
  localization:
    en: "Sorry, user not found. Please try again."
    th: "ขออภัย ไม่พบข้อมูลผู้ใช้งาน กรุณาลองใหม่อีกครั้ง"

invalid_maximum_size:
  code: 1006
  localization:
    en: "File upload have a maximum limit. Please try again"
    th: "ไฟล์ที่อัปโหลด มีขนาดเกินกำหนด กรุณาลองใหม่อีกครั้ง"

invalid_prefix_path_upload:
  code: 1007
  localization:
    en: "Prefix path for the upload file is invalid. Please try again."
    th: "พาร์ทไฟล์สำหรับอัพโหลดไฟล์ไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

upload_file_fail:
  code: 1027
  localization:
    en: "Upload file fail. Please try again."
    th: "อัพโหลดไฟล์ไม่สำเร็จ กรุณาลองใหม่อีกครั้ง"

ldap:
  group_not_exist:
    code: 2000
    localization:
      en: "Group does not exist. Please try again"
      th: "ไม่พบกลุ่มดังกล่าวใน ldap กรุณาลองใหม่อีกครั้ง"

  user_not_exist:
    code: 2001
    localization:
      en: "User does not exist. Please try again"
      th: "ไม่พบผู้ใช้งานดังกล่าวใน ldap กรุณาลองใหม่อีกครั้ง"

  too_many_entries:
    code: 2002
    localization:
      en: "Too many entries returned. Please try again"
      th: "รายการที่พบมากกว่า 1 รายการใน ldap กรุณาลองใหม่อีกครั้ง"

  user_already_exist:
    code: 2003
    localization:
      en: "User already exist. Please try again"
      th: "มีข้อมูลผู้ใช้งานดังกล่าวแล้ว กรุณาลองใหม่อีกครั้ง"

  data_not_exist:
    code: 2004
    localization:
      en: "Data does not exist. Please try again"
      th: "ไม่พบข้อมูลดังกล่าวใน ldap กรุณาลองใหม่อีกครั้ง"

# These are what we response to our internal services
internal:
  success:
    code: 0
    localization:
      en: "Success"
      th: "สำเร็จ"

  general:
    code: 500
    localization:
      en: "System cannot process this request at the moment. Please try again later"
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  bad_request:
    code: 400
    localization:
      en: "System cannot process this request at the moment. Please try again later"
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  connection_error:
    code: 500
    localization:
      en: "Connection error. Please try again"
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  database_not_found:
    code: 404
    localization:
      en: "Database not found. Please try again"
      th: "ขออภัย ไม่พบข้อมูลในระบบ กรุณาลองใหม่อีกครั้ง"

  unauthorized:
    code: 401
    localization:
      en: "The system does not allow you to access the request. Please try again later"
      th: "ขออภัย ระบบไม่อนุญาตให้คุณเข้าถึงการร้องขอได้ กรุณาลองใหม่อีกครั้ง"